### ISSUE TITLE
兼容IE11

### ISSUE THREAD

**Issue by Luluda** [xxholly32/vuepress-demo#1]
你好我试了下你的配置，想兼容ie11，但没有起作用；
下载了你的仓库后run dev，在ie11上看也有报错，希望能交流下这个问题，期待你的回复~

**Comment by xxholly32** [comment]
现在纯vuepress项目是可以在ie11跑的

这个在ie11不运行主要原因是vuepress 对于一些node_modules 内部的一些包没有做babel-loader的翻译，我们以前是有ui库，比如我的项目引入了elementui，那么在webpack的时候要做一些配置

现在还在做一些别的工作能够方便这块，vue-cli的话是有配置的，vuepress我提了issues，最近没时间，我也提了issues，应该会在最近[提pr去解决这个问题](https://github.com/vuejs/vuepress/issues/2031)

最早这个项目后面和一个韩国友人讨论最终用他的方案解决的，可以参考 [讨论地址](https://github.com/vuejs/vuepress/issues/1411)

**Comment by xxholly32** [comment]
我试了下我的demo好像是ok的

**Comment by Luluda** [comment]
> 我试了下我的demo好像是ok的

嗯嗯后来再试了下发现run dev不行，run build后是可以的，感谢~
